/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "rcc.h"
#include "RCC_config.h"
#include "GPIO_interface.h"

int main(void)
{
	//RCC_set_CLKStatus(HSI,ON);
	RCC_APB2_enableClock(4);
	RCC_APB2_enableClock(3);
	RCC_APB2_enableClock(2);

	Pin_Config_t led_pin=
	{

	.Port=PORTC,
    .Pin=PIN13,
	.Mode=Output_50MHZ,
	.output_mode=GP_output_PP,

	};



	GPIO_INIT(&led_pin);

	//set_reset_pin(PORTC,PIN13,On);
	Tog_Pin(PORTC,PIN13);
	Tog_Pin(PORTC,PIN13);
	Tog_Pin(PORTC,PIN13);
	Tog_Pin(PORTC,PIN13);

	for(;;);
}
